# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TampereSYKEPlugin
                                 A QGIS plugin
 Lisäosalla saa tuotua SYKE:n pohjavesiaineiston kaavoituksen tietokantaan
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-09-14
        copyright            : (C) 2018 by Gispo Oy
        email                : erno@gispo.fi
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TampereSYKEPlugin class from file TampereSYKEPlugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .syke_tampere_plugin import TampereSYKEPlugin
    return TampereSYKEPlugin(iface)
